export const LOAD_APP = "LOAD_APP";
export const LOAD_APP_ATTEMPT = "LOAD_APP_ATTEMPT";
export const LOAD_APP_SUCCESS = "LOAD_APP_SUCCESS";
export const LOAD_APP_FAIL = "LOAD_APP_FAIL";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const STICKY_MENU_ACTIVE = "STICKY_MENU_ACTIVE";
export const STICKY_MENU_DEACTIVE = "STICKY_MENU_DEACTIVE";

export const SIDE_MENU_OPEN = "SIDE_MENU_OPEN";
export const SIDE_MENU_CLOSE = "SIDE_MENU_CLOSE";
export const SIDE_MENU_TOGGLE = "SIDE_MENU_TOGGLE";
